---
about:
  markdown: 'https://raw.githubusercontent.com/binkoni/binkoni/main/README.md'
apps:
  - name: 'jamo'
    git: 'https://github.com/gonnux/jamo'
    site: 'https://gonapps.github.io/jamo'
    image: 'https://images.unsplash.com/photo-1578648693974-9438ebc063bb'

  - name: 'stellar-fighter'
    git: 'https://github.com/stellar-fighter/stellar-fighter'
    site: 'https://stellar-fighter.github.io/stellar-fighter'
    image: 'https://avatars2.githubusercontent.com/u/48615526'

projects:
  - name: 'vinbero'
    git: 'https://github.com/vinbero/vinbero'
    site: 'https://github.com/vinbero/vinbero'
    readme: 'https://raw.githubusercontent.com/vinbero/vinbero/master/README.md'
    image: 'https://raw.githubusercontent.com/vinbero/vinbero/master/img/vinbero.png'
