apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    cert-manager.io/cluster-issuer: site-cluster-issuer
spec:
  rules:
    - host: gonnux.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: site-service
                port:
                  number: 80
  tls:
    - secretName: site-secret
      hosts:
        - gonnux.com
