apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: site-cluster-issuer
spec:
  acme:
    email: binkoni@gonnux.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: site-secret
    solvers:
    - http01:
        ingress:
          class: traefik
