apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gonnux-site.fullname" . }}-ingress
  labels:
  {{- include "gonnux-site.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ include "gonnux-site.fullname" . }}-cluster-issuer
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "gonnux-site.fullname" . }}-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "gonnux-site.fullname" . }}-tls-secret
