apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gonnux-site.fullname" . }}-ingress
  labels:
  {{- include "gonnux-site.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ include "gonnux-site.fullname" . }}-cluster-issuer
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "gonnux-site.fullname" . }}-middleware@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "gonnux-site.fullname" . }}-service
            port:
              number: 80
  tls:
  - secretName: {{ include "gonnux-site.fullname" . }}-tls-secret
    hosts:
    - {{ .Values.ingress.host }}
    